name: Hi context
on: push
env:
  mascot: mxdr-cust-dev
  
jobs:
  windows_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hi ${{ env.mascot }}' 
      - run: echo 'Hi ${{ env.stepenv }}'  
        env:
          stepenv: dev1
  linux_job:
    runs-on: ubuntu-latest
    env:
      jobenv: dev2
    steps:
      - run: echo 'Hi ${{ env.jobenv }}'  
